[package]

name = "servo-skia"
version = "0.20130412.8"
authors = ["The Skia Project Developers and The Servo Project Developers"]
description = "2D graphic library for drawing Text, Geometries, and Images"
license = "BSD-3-Clause"
repository ="https://github.com/servo/skia/"
homepage = "https://skia.org/"
links = "skia"
build = "build.rs"
exclude = [
    "experimental/*",
    "expectations/*",
    "gm/tests/*",
    "gm/rebaseline_server/*",
    "platform_tools/android/bin/*",
    "platform_tools/android/examples/*",
    "platform_tools/android/tests/*",
    "tools/*",
    "tests/*",
]

[lib]
name = "skia"

[dependencies]
euclid = "0.6.1"
gleam = "0.2"
libc = "0.2"
servo-glutin = "0.4"
expat-sys = "2.1.1"

[target.i686-unknown-linux-gnu.dependencies]
servo-fontconfig = "0.2"
servo-freetype-sys = "2.4.11"
x11 = { version = "2.0.0", features = ["xlib"] }
glx = "0.1.0"

[target.x86_64-unknown-linux-gnu.dependencies]
servo-fontconfig = "0.2"
servo-freetype-sys = "2.4.11"
x11 = { version = "2.0.0", features = ["xlib"] }
glx = "0.1.0"

[target.arm-unknown-linux-gnueabihf.dependencies]
servo-fontconfig = "0.2"
servo-freetype-sys = "2.4.11"
x11 = { version = "2.0.0", features = ["xlib"] }
glx = "0.1.0"

[target.armv7-unknown-linux-gnueabihf.dependencies]
servo-fontconfig = "0.2"
servo-freetype-sys = "2.4.11"
x11 = { version = "2.0.0", features = ["xlib"] }
glx = "0.1.0"

[target.aarch64-unknown-linux-gnu.dependencies]
servo-fontconfig = "0.2"
servo-freetype-sys = "2.4.11"
x11 = { version = "2.0.0", features = ["xlib"] }
glx = "0.1.0"

[target.arm-linux-androideabi.dependencies]
servo-fontconfig = "0.2"
servo-freetype-sys = "2.4.11"
servo-egl = "0.2"

[target.x86_64-pc-windows-gnu.dependencies]
servo-fontconfig = "0.2"
servo-freetype-sys = "2.4.11"

[target.x86_64-apple-darwin.dependencies]
cgl = "0.1"
io-surface = "0.2.0"
