[package]

name = "skia"
version = "0.0.20130412"
authors = ["The Skia Project Developers and The Servo Project Developers"]
links = "skia"
build = "build.rs"

[dependencies]
euclid = "0.2"
gleam = "0.1"
libc = "0.1"

[dependencies.expat-sys]
git = "https://github.com/servo/libexpat"

[target.i686-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.x86_64-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.arm-unknown-linux-gnueabihf.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.aarch64-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.arm-linux-androideabi.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.arm-linux-androideabi.dependencies.egl]
git = "https://github.com/servo/rust-egl"

[target.i686-unknown-linux-gnu.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.x86_64-unknown-linux-gnu.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.arm-unknown-linux-gnueabihf.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.aarch64-unknown-linux-gnu.dependencies.glx]
git = "https://github.com/servo/rust-glx"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "2.0.0"
features = ["xlib"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "2.0.0"
features = ["xlib"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "2.0.0"
features = ["xlib"]

[target.aarch64-unknown-linux-gnu.dependencies.x11]
version = "2.0.0"
features = ["xlib"]

[target.x86_64-apple-darwin.dependencies]
cgl = "0.1"

[target.x86_64-apple-darwin.dependencies.io-surface]
git = "https://github.com/servo/io-surface-rs"

